apiVersion: v1
kind: Namespace
metadata:
  name: pkarunas
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: pkarunas
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMC4xMi4xMC4xODo4MTIzIjogewoJCQkiYXV0aCI6ICJTbVZ1YTJsdWN6bzRNalJoZEcweU1RPT0iCgkJfSwKCQkiMTAuMTIuMTEuMTg6ODEyMyI6IHsKCQkJImF1dGgiOiAiU21WdWEybHVjem80TWpSaGRHMHlNUT09IgoJCX0sCgkJIjEwLjEyLjEyLjE1OjgxMjQiOiB7CgkJCSJhdXRoIjogIlNtVnVhMmx1Y3pvNE1qUmhkRzB5TVE9PSIKCQl9LAoJCSIxMC4xMi4xMi4xODo4MTI0IjogewoJCQkiYXV0aCI6ICJTbVZ1YTJsdWN6bzRNalJoZEcweU1RPT0iCgkJfSwKCQkiMTAuMTIuMTMuMTU6ODEyNCI6IHsKCQkJImF1dGgiOiAiU21WdWEybHVjem80TWpSaGRHMHlNUT09IgoJCX0sCgkJIjEwLjEyLjcuMTM6ODEyMyI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZPREp0Y1dRMk5IRT0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjggKGxpbnV4KSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkarunas-tomcat
  namespace: pkarunas
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 50%
  selector:
    matchLabels:
      app: pkarunas-tomcat
  template:
    metadata:
      labels:
        app: pkarunas-tomcat
    spec:
      containers:
      - name: pkarunas-tomcat
        image: replace_string
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /helloworld-ws/
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /helloworld-ws/
            port: 8080
            httpHeaders:
            - name: Server
              value: DunnoWhy
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tomcat
  name: pkarunas-svc
  namespace: pkarunas
spec:
  ports:
  - port: 80
    nodePort: 30170
    protocol: TCP
    targetPort: 8080
  selector:
    app: pkarunas-tomcat
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pkarunas-ingress
  namespace: pkarunas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /helloworld-ws/
spec:
  rules:
  - host: helloworld-app.k8s.pkarunas.playpit.by
    http:
      paths: 
      - path: /
        backend:
          serviceName: pkarunas-svc
          servicePort: 80
